### ISSUE TITLE
Pretrained Modols

### ISSUE THREAD

**Issue by YoushaaMurhij** [dingwoai/FairMOT-BDD100K#2]
Are you planning to share your .pth files? 
Which .zip files I need to download from BDD100K website?

**Comment by dingwoai** [comment]
Pretrained .pth files are nothing special but pretrained detection models (centernet) on bdd100k dataset. 

Plz refer to [this website](https://bdd-data.berkeley.edu/wad-2020.html) for all you need to know about the dataset and evaluation metrics for training a tracker.
