### ISSUE TITLE
The output results.txt has only one class id

### ISSUE THREAD

**Issue by RamkumarSakthivel** [dingwoai/FairMOT-BDD100K#5]
Though there are 11 classes in the BDD-MOT dataset, during inference only one class id is displayed for all objects. The network also has object recognition to identify call labels right? Where can we get the class ids during inference?

**Comment by RamkumarSakthivel** [comment]
My bad had to change to 'bdd' instead of 'mot'

**Comment by supperted825** [comment]
Hi @RamkumarSakthivel , may I know where you had to change bdd to mot to achieve multi-class tracking?
