### ISSUE TITLE
data  process

### ISSUE THREAD

**Issue by CompliceU** [dingwoai/FairMOT-BDD100K#8]
Hello, when I am processing data, there is no part of your tracking in the downloaded data. I don't know if the data I track is missing. I don't know if I can give some guidance, thank you @dingwoai

**Comment by dingwoai** [comment]
On the official website of bdd100k data, you can download MOT data.
MOT means Multi Object Tracking.

**Comment by CompliceU** [comment]
Sorry, when I download the MOT separately, it always shows an error and cannot be downloaded. Can you share this part of the data, thank you very much, is Baidu Cloud OK? @dingwoai
